#!/usr/bin/env python3

import socket

HOST = input("Введите IP-адрес сервера (по умолчанию 127.0.0.1): ")
if not HOST:
    HOST = '127.0.0.1'
PORT = 1303

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    data = s.recv(1024)

print(data.decode())
